//UC3

/**
 * OOPSBannerApp UC2 – Banner Display Application
 * OOPSBannerApp UC3 - OOPS Banner Application (Use Case 3)
 *
 * This class demonstrates the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
 * console using individual print statements for each line, creating a decorative
 * text effect.
 * This class extends the functionality of Use Case 2 by improving the way the "OOPS" banner
 * is constructed and displayed. It focuses on enhancing code readability and efficiency
 * by utilizing the String.join() method to create each line of the banner. This approach
 * overcomes the drawbacks of using the + operator for string concatenation, which can lead
 * to code inefficiency due to the creation of multiple intermediate String objects in memory.
 *
 * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters O, O, P, and S in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output.
 * </p>
 *
 * @author Rajbir Mohan Chatterjee
 * @version 2.0
 * @author Developer
 * @version 3.0
 */

// Extend the User Story 1 to display the message "OOPS" in a banner format
// using characters formed by spaces and asterisks (*) to create a visual
// effect for each letter in the message. Use print statements for each line
// instead of a loop.
// Extend use case UC2 to use String.join() method to create each line of the "OOPS" banner
// instead of concatenating strings with the + operator. This is essentially to overcome the
// drawbacks of using the + operator for string concatenation which essentially creates
// multiple intermediate String objects in memory leading to inefficiency.

// Hint: Use String.join(" ", ...) to join the parts of each line with spaces.

public class UC_3 
{
    public static void main(String[] args) 
    {
        String line1 = String.join("  ",
                " ***** ",
                " ***** ",
                " ***** ",
                " ***** ");

        String line2 = String.join("  ",
                " *   * ",
                " *   * ",
                " *   * ",
                " *     ");

        String line3 = String.join("  ",
                " *   * ",
                " *   * ",
                " *   * ",
                " *     ");

        String line4 = String.join("  ",
                " *   * ",
                " *   * ",
                " ***** ",
                " ***** ");

        String line5 = String.join("  ",
                " *   * ",
                " *   * ",
                " *     ",
                "     * ");

        String line6 = String.join("  ",
                " *   * ",
                " *   * ",
                " *     ",
                "     * ");

        String line7 = String.join("  ",
                " ***** ",
                " ***** ",
                " *     ",
                " ***** ");

        System.out.println(line1);
        System.out.println(line2);
        System.out.println(line3);
        System.out.println(line4);
        System.out.println(line5);
        System.out.println(line6);
        System.out.println(line7);
    }
}
